kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: xyz
  name: azure-devops-deploy-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-devops-deploy-manager
  namespace: xyz
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-devops-deploy-role
  apiGroup: rbac.authorization.k8s.io

apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-marvel-last
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-marvel-last
  template:
    metadata:
      labels:
        app: azure-marvel-last
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-marvel-last
        image: cavicavi.azurecr.io/marvelf317
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-marvel-last
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-marvel-last